### ISSUE TITLE
Infografía Hilos

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/infografia-de-hilos-IsraelNicolas61#2]
[Infografia_Hilos_Israel_Nicolas_Perez.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-IsraelNicolas61/files/6459965/Infografia_Hilos_Israel_Nicolas_Perez.pdf)

**Comment by Rigoberto2001** [comment]
CALIFICACIÓN: 18/20

**Comment by Rigoberto2001** [comment]
CALIFICACIÓN: 18/20.

CALIFICÓ: RIGOBERTO RAMIREZ NICOLÁS

**Comment by josealfredo79** [comment]
Bien hecho y revisado
